apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: abdullah-tawazun
  name: mysql-pv
  labels:
    type: local
    name: abdullah
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"