apiVersion: v1
kind: Service
metadata:
  namespace: abdullah-tawazun
  name: webapp-service
  labels:
    app: webapp-service
    name: abdullah
spec:
 selector:
   app: webapp
 type: NodePort
 ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30058