apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: abdullah-tawazun
  name: tawazun-resource-quota
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 10Gi
    limits.cpu: "20"
    limits.memory: 20Gi
    