apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: abdullah-tawazun
  name: mysql-pv-claim
  labels:
    type: local
    name: abdullah
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi