apiVersion: v1
kind: Service
metadata:
  namespace: abdullah-tawazun
  name: mysql-db
  labels:
    name: abdullah
spec:
 selector:
    app: mysql-db
 type: ClusterIP
 ports:
    - protocol: TCP
      port: 3306