apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: abdullah-tawazun
  name: webapp
  labels:
    app: webapp
    name: abdullah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: abdullah01455/tawazun-v1
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
            requests:
              memory: "1Gi"
              cpu: "1"

          name: webapp
          env:
            - name: DB_URL
              value: mysql-db
            - name: DB_PORT
              value: '3306'  
            - name: DB_NAME
              value: tawazun  
            - name: DB_USERNAME
              value: root  
            - name: DB_PASSWORD
              value: DevOps2022
          ports:          
           - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /home
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /home
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /home
              port: 8080
            failureThreshold: 30
            periodSeconds: 10